version: '3.8'
services:
  doc-analyzer:
    image: devaman21/doc-analyzer:${IMAGE_TAG}
    restart: unless-stopped
    ports:
      - "80:8000"
    env_file:
      - .env
    volumes:
      - uploads_data:/usr/python/app/doc-analyzer/app/uploads

volumes:
  uploads_data:
